### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,3,1],[6,8,11,10,7]]).transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = np.mean(a, axis=0)

In [4]:
mean_a

array([2. , 8.4])

In [5]:
a_centered = a - mean_a

In [6]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [7]:
a_centered.T[0]

array([-1.,  0.,  1.,  1., -1.])

In [8]:
a_centered.T[1]

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [9]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [10]:
a_centered.shape[0]

5

In [11]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

In [12]:
np.cov(a.T)[0, 1]

2.0